package catalog_test

import (
	"testing"

	"github.com/Kyaxris-Labs/Noctaxris/internal/catalog"
)

func TestKnownActionPhase4(t *testing.T) {
	known := []string{
		// STS (11)
		catalog.ActionSTSGetCallerIdentity,
		catalog.ActionSTSAssumeRole,
		catalog.ActionSTSGetSessionToken,
		catalog.ActionSTSGetFederationToken,
		catalog.ActionSTSAssumeRoleWithSAML,
		catalog.ActionSTSAssumeRoleWithWebIdentity,
		catalog.ActionSTSAssumeRoot,
		catalog.ActionSTSDecodeAuthorizationMessage,
		catalog.ActionSTSGetAccessKeyInfo,
		catalog.ActionSTSGetDelegatedAccessToken,
		catalog.ActionSTSGetWebIdentityToken,
		// Organizations (CreateAccount + depth)
		catalog.ActionOrgsCreateAccount,
		catalog.ActionOrgsDescribeCreateAccountStatus,
		catalog.ActionOrgsListAccounts,
		catalog.ActionOrgsCreateOrganizationalUnit,
		catalog.ActionOrgsListOrganizationalUnitsForParent,
		catalog.ActionOrgsEnablePolicyType,
		catalog.ActionOrgsCreatePolicy,
		catalog.ActionOrgsAttachPolicy,
		catalog.ActionOrgsDetachPolicy,
		catalog.ActionOrgsDescribePolicy,
		// IAM lab
		catalog.ActionIAMCreateUser,
		catalog.ActionIAMGetUser,
		catalog.ActionIAMListUsers,
		catalog.ActionIAMDeleteUser,
		catalog.ActionIAMCreateAccessKey,
		catalog.ActionIAMDeleteAccessKey,
		catalog.ActionIAMListAccessKeys,
		catalog.ActionIAMUpdateAccessKey,
		catalog.ActionIAMCreatePolicy,
		catalog.ActionIAMGetPolicy,
		catalog.ActionIAMListPolicies,
		catalog.ActionIAMDeletePolicy,
		catalog.ActionIAMAttachUserPolicy,
		catalog.ActionIAMDetachUserPolicy,
		catalog.ActionIAMAttachRolePolicy,
		catalog.ActionIAMDetachRolePolicy,
		catalog.ActionIAMListAttachedUserPolicies,
		catalog.ActionIAMListAttachedRolePolicies,
		catalog.ActionIAMPutUserPolicy,
		catalog.ActionIAMGetUserPolicy,
		catalog.ActionIAMDeleteUserPolicy,
		catalog.ActionIAMListUserPolicies,
		catalog.ActionIAMPutRolePolicy,
		catalog.ActionIAMGetRolePolicy,
		catalog.ActionIAMDeleteRolePolicy,
		catalog.ActionIAMListRolePolicies,
		catalog.ActionIAMCreateRole,
		catalog.ActionIAMGetRole,
		catalog.ActionIAMListRoles,
		catalog.ActionIAMDeleteRole,
		catalog.ActionIAMUpdateAssumeRolePolicy,
		catalog.ActionIAMCreateGroup,
		catalog.ActionIAMDeleteGroup,
		catalog.ActionIAMGetGroup,
		catalog.ActionIAMListGroups,
		catalog.ActionIAMAddUserToGroup,
		catalog.ActionIAMRemoveUserFromGroup,
		catalog.ActionIAMAttachGroupPolicy,
		catalog.ActionIAMDetachGroupPolicy,
		catalog.ActionIAMListAttachedGroupPolicies,
		catalog.ActionIAMPutGroupPolicy,
		catalog.ActionIAMGetGroupPolicy,
		catalog.ActionIAMDeleteGroupPolicy,
		catalog.ActionIAMListGroupPolicies,
		catalog.ActionIAMPutUserPermissionsBoundary,
		catalog.ActionIAMGetUserPermissionsBoundary,
		catalog.ActionIAMDeleteUserPermissionsBoundary,
		catalog.ActionIAMPutRolePermissionsBoundary,
		catalog.ActionIAMGetRolePermissionsBoundary,
		catalog.ActionIAMDeleteRolePermissionsBoundary,
		catalog.ActionIAMCreateInstanceProfile,
		catalog.ActionIAMDeleteInstanceProfile,
		catalog.ActionIAMGetInstanceProfile,
		catalog.ActionIAMAddRoleToInstanceProfile,
		catalog.ActionIAMRemoveRoleFromInstanceProfile,
		catalog.ActionIAMListInstanceProfiles,
		catalog.ActionIAMCreateOpenIDConnectProvider,
		catalog.ActionIAMDeleteOpenIDConnectProvider,
		catalog.ActionIAMListOpenIDConnectProviders,
		catalog.ActionIAMGetOpenIDConnectProvider,
		catalog.ActionIAMCreateSAMLProvider,
		catalog.ActionIAMDeleteSAMLProvider,
		catalog.ActionIAMListSAMLProviders,
		catalog.ActionIAMGetSAMLProvider,
		catalog.ActionIAMCreateVirtualMFADevice,
		catalog.ActionIAMEnableMFADevice,
		catalog.ActionIAMListMFADevices,
		catalog.ActionIAMDeactivateMFADevice,
		// KMS lab
		catalog.ActionKMSCreateKey,
		catalog.ActionKMSDescribeKey,
		catalog.ActionKMSListKeys,
		catalog.ActionKMSEnableKey,
		catalog.ActionKMSDisableKey,
		catalog.ActionKMSGetKeyPolicy,
		catalog.ActionKMSPutKeyPolicy,
		catalog.ActionKMSEncrypt,
		catalog.ActionKMSDecrypt,
		catalog.ActionKMSGenerateDataKey,
		catalog.ActionKMSGenerateDataKeyWithoutPlaintext,
		catalog.ActionKMSCreateGrant,
		catalog.ActionKMSListGrants,
		catalog.ActionKMSRetireGrant,
		catalog.ActionKMSRevokeGrant,
		catalog.ActionKMSCreateAlias,
		catalog.ActionKMSListAliases,
		catalog.ActionKMSDeleteAlias,
		catalog.ActionKMSUpdateAlias,
		catalog.ActionKMSScheduleKeyDeletion,
		catalog.ActionKMSCancelKeyDeletion,
		catalog.ActionKMSEnableKeyRotation,
		catalog.ActionKMSDisableKeyRotation,
		catalog.ActionKMSGetKeyRotationStatus,
		catalog.ActionKMSReEncryptFrom,
		catalog.ActionKMSReEncryptTo,
		// S3 lab
		catalog.ActionS3CreateBucket,
		catalog.ActionS3DeleteBucket,
		catalog.ActionS3ListAllMyBuckets,
		catalog.ActionS3ListBucket,
		catalog.ActionS3GetBucketPolicy,
		catalog.ActionS3PutBucketPolicy,
		catalog.ActionS3DeleteBucketPolicy,
		catalog.ActionS3GetObject,
		catalog.ActionS3PutObject,
		catalog.ActionS3DeleteObject,
		catalog.ActionS3PutEncryptionConfiguration,
		catalog.ActionS3GetEncryptionConfiguration,
		catalog.ActionS3DeleteEncryptionConfiguration,
		// DynamoDB lab
		catalog.ActionDynamoDBCreateTable,
		catalog.ActionDynamoDBDescribeTable,
		catalog.ActionDynamoDBDeleteTable,
		catalog.ActionDynamoDBListTables,
		catalog.ActionDynamoDBUpdateTable,
		catalog.ActionDynamoDBPutItem,
		catalog.ActionDynamoDBGetItem,
		catalog.ActionDynamoDBDeleteItem,
		catalog.ActionDynamoDBUpdateItem,
		catalog.ActionDynamoDBQuery,
		catalog.ActionDynamoDBScan,
		catalog.ActionDynamoDBBatchGetItem,
		catalog.ActionDynamoDBBatchWriteItem,
		catalog.ActionDynamoDBPutResourcePolicy,
		catalog.ActionDynamoDBGetResourcePolicy,
		catalog.ActionDynamoDBDeleteResourcePolicy,
		catalog.ActionDynamoDBUpdateTimeToLive,
		catalog.ActionDynamoDBDescribeTimeToLive,
		// SQS lab
		catalog.ActionSQSCreateQueue,
		catalog.ActionSQSGetQueueUrl,
		catalog.ActionSQSGetQueueAttributes,
		catalog.ActionSQSSetQueueAttributes,
		catalog.ActionSQSDeleteQueue,
		catalog.ActionSQSListQueues,
		catalog.ActionSQSPurgeQueue,
		catalog.ActionSQSSendMessage,
		catalog.ActionSQSReceiveMessage,
		catalog.ActionSQSDeleteMessage,
		catalog.ActionSQSSendMessageBatch,
		catalog.ActionSQSDeleteMessageBatch,
		catalog.ActionSQSChangeMessageVisibility,
		// Lambda lab
		catalog.ActionLambdaCreateFunction,
		catalog.ActionLambdaGetFunction,
		catalog.ActionLambdaDeleteFunction,
		catalog.ActionLambdaListFunctions,
		catalog.ActionLambdaUpdateFunctionCode,
		catalog.ActionLambdaUpdateFunctionConfiguration,
		catalog.ActionLambdaInvoke,
	}
	for _, action := range known {
		if !catalog.KnownAction(action) {
			t.Fatalf("KnownAction(%q) = false, want true", action)
		}
	}
}

func TestKnownActionUnknown(t *testing.T) {
	cases := []string{
		"",
		"s3:GetBucketAcl",
		"GetCallerIdentity",
		"sts:getcalleridentity",
		"sts:UnknownAction",
		"kms:ReEncrypt",
		"dynamodb:CreateGlobalTable",
		"sqs:CreateFIFOQueue",
		"lambda:PublishVersion",
	}
	for _, action := range cases {
		if catalog.KnownAction(action) {
			t.Fatalf("KnownAction(%q) = true, want false", action)
		}
	}
}

func TestActionConstants(t *testing.T) {
	cases := map[string]string{
		catalog.ActionSTSGetCallerIdentity:                 "sts:GetCallerIdentity",
		catalog.ActionSTSAssumeRole:                        "sts:AssumeRole",
		catalog.ActionSTSGetSessionToken:                   "sts:GetSessionToken",
		catalog.ActionSTSGetFederationToken:                "sts:GetFederationToken",
		catalog.ActionSTSAssumeRoleWithSAML:                "sts:AssumeRoleWithSAML",
		catalog.ActionSTSAssumeRoleWithWebIdentity:         "sts:AssumeRoleWithWebIdentity",
		catalog.ActionSTSAssumeRoot:                        "sts:AssumeRoot",
		catalog.ActionSTSDecodeAuthorizationMessage:        "sts:DecodeAuthorizationMessage",
		catalog.ActionSTSGetAccessKeyInfo:                  "sts:GetAccessKeyInfo",
		catalog.ActionSTSGetDelegatedAccessToken:           "sts:GetDelegatedAccessToken",
		catalog.ActionSTSGetWebIdentityToken:               "sts:GetWebIdentityToken",
		catalog.ActionOrgsCreateAccount:                    "organizations:CreateAccount",
		catalog.ActionOrgsDescribeCreateAccountStatus:      "organizations:DescribeCreateAccountStatus",
		catalog.ActionOrgsListAccounts:                     "organizations:ListAccounts",
		catalog.ActionOrgsCreateOrganizationalUnit:         "organizations:CreateOrganizationalUnit",
		catalog.ActionOrgsListOrganizationalUnitsForParent: "organizations:ListOrganizationalUnitsForParent",
		catalog.ActionOrgsEnablePolicyType:                 "organizations:EnablePolicyType",
		catalog.ActionOrgsCreatePolicy:                     "organizations:CreatePolicy",
		catalog.ActionOrgsAttachPolicy:                     "organizations:AttachPolicy",
		catalog.ActionOrgsDetachPolicy:                     "organizations:DetachPolicy",
		catalog.ActionOrgsDescribePolicy:                   "organizations:DescribePolicy",
		catalog.ActionIAMCreateUser:                        "iam:CreateUser",
		catalog.ActionIAMGetUser:                           "iam:GetUser",
		catalog.ActionIAMListUsers:                         "iam:ListUsers",
		catalog.ActionIAMDeleteUser:                        "iam:DeleteUser",
		catalog.ActionIAMCreateAccessKey:                   "iam:CreateAccessKey",
		catalog.ActionIAMDeleteAccessKey:                   "iam:DeleteAccessKey",
		catalog.ActionIAMListAccessKeys:                    "iam:ListAccessKeys",
		catalog.ActionIAMUpdateAccessKey:                   "iam:UpdateAccessKey",
		catalog.ActionIAMCreatePolicy:                      "iam:CreatePolicy",
		catalog.ActionIAMGetPolicy:                         "iam:GetPolicy",
		catalog.ActionIAMListPolicies:                      "iam:ListPolicies",
		catalog.ActionIAMDeletePolicy:                      "iam:DeletePolicy",
		catalog.ActionIAMAttachUserPolicy:                  "iam:AttachUserPolicy",
		catalog.ActionIAMDetachUserPolicy:                  "iam:DetachUserPolicy",
		catalog.ActionIAMAttachRolePolicy:                  "iam:AttachRolePolicy",
		catalog.ActionIAMDetachRolePolicy:                  "iam:DetachRolePolicy",
		catalog.ActionIAMListAttachedUserPolicies:          "iam:ListAttachedUserPolicies",
		catalog.ActionIAMListAttachedRolePolicies:          "iam:ListAttachedRolePolicies",
		catalog.ActionIAMPutUserPolicy:                     "iam:PutUserPolicy",
		catalog.ActionIAMGetUserPolicy:                     "iam:GetUserPolicy",
		catalog.ActionIAMDeleteUserPolicy:                  "iam:DeleteUserPolicy",
		catalog.ActionIAMListUserPolicies:                  "iam:ListUserPolicies",
		catalog.ActionIAMPutRolePolicy:                     "iam:PutRolePolicy",
		catalog.ActionIAMGetRolePolicy:                     "iam:GetRolePolicy",
		catalog.ActionIAMDeleteRolePolicy:                  "iam:DeleteRolePolicy",
		catalog.ActionIAMListRolePolicies:                  "iam:ListRolePolicies",
		catalog.ActionIAMCreateRole:                        "iam:CreateRole",
		catalog.ActionIAMGetRole:                           "iam:GetRole",
		catalog.ActionIAMListRoles:                         "iam:ListRoles",
		catalog.ActionIAMDeleteRole:                        "iam:DeleteRole",
		catalog.ActionIAMUpdateAssumeRolePolicy:            "iam:UpdateAssumeRolePolicy",
		catalog.ActionIAMCreateGroup:                       "iam:CreateGroup",
		catalog.ActionIAMDeleteGroup:                       "iam:DeleteGroup",
		catalog.ActionIAMGetGroup:                          "iam:GetGroup",
		catalog.ActionIAMListGroups:                        "iam:ListGroups",
		catalog.ActionIAMAddUserToGroup:                    "iam:AddUserToGroup",
		catalog.ActionIAMRemoveUserFromGroup:               "iam:RemoveUserFromGroup",
		catalog.ActionIAMAttachGroupPolicy:                 "iam:AttachGroupPolicy",
		catalog.ActionIAMDetachGroupPolicy:                 "iam:DetachGroupPolicy",
		catalog.ActionIAMListAttachedGroupPolicies:         "iam:ListAttachedGroupPolicies",
		catalog.ActionIAMPutGroupPolicy:                    "iam:PutGroupPolicy",
		catalog.ActionIAMGetGroupPolicy:                    "iam:GetGroupPolicy",
		catalog.ActionIAMDeleteGroupPolicy:                 "iam:DeleteGroupPolicy",
		catalog.ActionIAMListGroupPolicies:                 "iam:ListGroupPolicies",
		catalog.ActionIAMPutUserPermissionsBoundary:        "iam:PutUserPermissionsBoundary",
		catalog.ActionIAMGetUserPermissionsBoundary:        "iam:GetUserPermissionsBoundary",
		catalog.ActionIAMDeleteUserPermissionsBoundary:     "iam:DeleteUserPermissionsBoundary",
		catalog.ActionIAMPutRolePermissionsBoundary:        "iam:PutRolePermissionsBoundary",
		catalog.ActionIAMGetRolePermissionsBoundary:        "iam:GetRolePermissionsBoundary",
		catalog.ActionIAMDeleteRolePermissionsBoundary:     "iam:DeleteRolePermissionsBoundary",
		catalog.ActionIAMCreateInstanceProfile:             "iam:CreateInstanceProfile",
		catalog.ActionIAMDeleteInstanceProfile:             "iam:DeleteInstanceProfile",
		catalog.ActionIAMGetInstanceProfile:                "iam:GetInstanceProfile",
		catalog.ActionIAMAddRoleToInstanceProfile:          "iam:AddRoleToInstanceProfile",
		catalog.ActionIAMRemoveRoleFromInstanceProfile:     "iam:RemoveRoleFromInstanceProfile",
		catalog.ActionIAMListInstanceProfiles:              "iam:ListInstanceProfiles",
		catalog.ActionIAMCreateOpenIDConnectProvider:       "iam:CreateOpenIDConnectProvider",
		catalog.ActionIAMDeleteOpenIDConnectProvider:       "iam:DeleteOpenIDConnectProvider",
		catalog.ActionIAMListOpenIDConnectProviders:        "iam:ListOpenIDConnectProviders",
		catalog.ActionIAMGetOpenIDConnectProvider:          "iam:GetOpenIDConnectProvider",
		catalog.ActionIAMCreateSAMLProvider:                "iam:CreateSAMLProvider",
		catalog.ActionIAMDeleteSAMLProvider:                "iam:DeleteSAMLProvider",
		catalog.ActionIAMListSAMLProviders:                 "iam:ListSAMLProviders",
		catalog.ActionIAMGetSAMLProvider:                   "iam:GetSAMLProvider",
		catalog.ActionIAMCreateVirtualMFADevice:            "iam:CreateVirtualMFADevice",
		catalog.ActionIAMEnableMFADevice:                   "iam:EnableMFADevice",
		catalog.ActionIAMListMFADevices:                    "iam:ListMFADevices",
		catalog.ActionIAMDeactivateMFADevice:               "iam:DeactivateMFADevice",
		catalog.ActionKMSCreateKey:                         "kms:CreateKey",
		catalog.ActionKMSDescribeKey:                       "kms:DescribeKey",
		catalog.ActionKMSListKeys:                          "kms:ListKeys",
		catalog.ActionKMSEnableKey:                         "kms:EnableKey",
		catalog.ActionKMSDisableKey:                        "kms:DisableKey",
		catalog.ActionKMSGetKeyPolicy:                      "kms:GetKeyPolicy",
		catalog.ActionKMSPutKeyPolicy:                      "kms:PutKeyPolicy",
		catalog.ActionKMSEncrypt:                           "kms:Encrypt",
		catalog.ActionKMSDecrypt:                           "kms:Decrypt",
		catalog.ActionKMSGenerateDataKey:                   "kms:GenerateDataKey",
		catalog.ActionKMSGenerateDataKeyWithoutPlaintext:   "kms:GenerateDataKeyWithoutPlaintext",
		catalog.ActionKMSCreateGrant:                       "kms:CreateGrant",
		catalog.ActionKMSListGrants:                        "kms:ListGrants",
		catalog.ActionKMSRetireGrant:                       "kms:RetireGrant",
		catalog.ActionKMSRevokeGrant:                       "kms:RevokeGrant",
		catalog.ActionKMSCreateAlias:                       "kms:CreateAlias",
		catalog.ActionKMSListAliases:                       "kms:ListAliases",
		catalog.ActionKMSDeleteAlias:                       "kms:DeleteAlias",
		catalog.ActionKMSUpdateAlias:                       "kms:UpdateAlias",
		catalog.ActionKMSScheduleKeyDeletion:               "kms:ScheduleKeyDeletion",
		catalog.ActionKMSCancelKeyDeletion:                 "kms:CancelKeyDeletion",
		catalog.ActionKMSEnableKeyRotation:                 "kms:EnableKeyRotation",
		catalog.ActionKMSDisableKeyRotation:                "kms:DisableKeyRotation",
		catalog.ActionKMSGetKeyRotationStatus:              "kms:GetKeyRotationStatus",
		catalog.ActionKMSReEncryptFrom:                     "kms:ReEncryptFrom",
		catalog.ActionKMSReEncryptTo:                       "kms:ReEncryptTo",
		catalog.ActionS3CreateBucket:                       "s3:CreateBucket",
		catalog.ActionS3DeleteBucket:                       "s3:DeleteBucket",
		catalog.ActionS3ListAllMyBuckets:                   "s3:ListAllMyBuckets",
		catalog.ActionS3ListBucket:                         "s3:ListBucket",
		catalog.ActionS3GetBucketPolicy:                    "s3:GetBucketPolicy",
		catalog.ActionS3PutBucketPolicy:                    "s3:PutBucketPolicy",
		catalog.ActionS3DeleteBucketPolicy:                 "s3:DeleteBucketPolicy",
		catalog.ActionS3GetObject:                          "s3:GetObject",
		catalog.ActionS3PutObject:                          "s3:PutObject",
		catalog.ActionS3DeleteObject:                       "s3:DeleteObject",
		catalog.ActionS3PutEncryptionConfiguration:           "s3:PutEncryptionConfiguration",
		catalog.ActionS3GetEncryptionConfiguration:           "s3:GetEncryptionConfiguration",
		catalog.ActionS3DeleteEncryptionConfiguration:        "s3:DeleteEncryptionConfiguration",
		catalog.ActionDynamoDBCreateTable:                  "dynamodb:CreateTable",
		catalog.ActionDynamoDBDescribeTable:                "dynamodb:DescribeTable",
		catalog.ActionDynamoDBDeleteTable:                  "dynamodb:DeleteTable",
		catalog.ActionDynamoDBListTables:                   "dynamodb:ListTables",
		catalog.ActionDynamoDBUpdateTable:                  "dynamodb:UpdateTable",
		catalog.ActionDynamoDBPutItem:                      "dynamodb:PutItem",
		catalog.ActionDynamoDBGetItem:                      "dynamodb:GetItem",
		catalog.ActionDynamoDBDeleteItem:                   "dynamodb:DeleteItem",
		catalog.ActionDynamoDBUpdateItem:                   "dynamodb:UpdateItem",
		catalog.ActionDynamoDBQuery:                        "dynamodb:Query",
		catalog.ActionDynamoDBScan:                         "dynamodb:Scan",
		catalog.ActionDynamoDBBatchGetItem:                 "dynamodb:BatchGetItem",
		catalog.ActionDynamoDBBatchWriteItem:               "dynamodb:BatchWriteItem",
		catalog.ActionDynamoDBPutResourcePolicy:            "dynamodb:PutResourcePolicy",
		catalog.ActionDynamoDBGetResourcePolicy:            "dynamodb:GetResourcePolicy",
		catalog.ActionDynamoDBDeleteResourcePolicy:         "dynamodb:DeleteResourcePolicy",
		catalog.ActionDynamoDBUpdateTimeToLive:             "dynamodb:UpdateTimeToLive",
		catalog.ActionDynamoDBDescribeTimeToLive:           "dynamodb:DescribeTimeToLive",
		catalog.ActionSQSCreateQueue:                       "sqs:CreateQueue",
		catalog.ActionSQSGetQueueUrl:                       "sqs:GetQueueUrl",
		catalog.ActionSQSGetQueueAttributes:                "sqs:GetQueueAttributes",
		catalog.ActionSQSSetQueueAttributes:                "sqs:SetQueueAttributes",
		catalog.ActionSQSDeleteQueue:                       "sqs:DeleteQueue",
		catalog.ActionSQSListQueues:                        "sqs:ListQueues",
		catalog.ActionSQSPurgeQueue:                        "sqs:PurgeQueue",
		catalog.ActionSQSSendMessage:                       "sqs:SendMessage",
		catalog.ActionSQSReceiveMessage:                    "sqs:ReceiveMessage",
		catalog.ActionSQSDeleteMessage:                     "sqs:DeleteMessage",
		catalog.ActionSQSSendMessageBatch:                  "sqs:SendMessageBatch",
		catalog.ActionSQSDeleteMessageBatch:                "sqs:DeleteMessageBatch",
		catalog.ActionSQSChangeMessageVisibility:           "sqs:ChangeMessageVisibility",
		catalog.ActionLambdaCreateFunction:                 "lambda:CreateFunction",
		catalog.ActionLambdaGetFunction:                    "lambda:GetFunction",
		catalog.ActionLambdaDeleteFunction:                 "lambda:DeleteFunction",
		catalog.ActionLambdaListFunctions:                  "lambda:ListFunctions",
		catalog.ActionLambdaUpdateFunctionCode:             "lambda:UpdateFunctionCode",
		catalog.ActionLambdaUpdateFunctionConfiguration:    "lambda:UpdateFunctionConfiguration",
		catalog.ActionLambdaInvoke:                         "lambda:InvokeFunction",
	}
	for got, want := range cases {
		if got != want {
			t.Fatalf("constant = %q, want %q", got, want)
		}
	}
}
