#!/usr/bin/env python3
"""Extract Action* const strings from actions.go into data/actions.json and zz_actions.go."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ACTIONS_GO = ROOT / "actions.go"
DATA = ROOT / "data"

ACTION_RE = re.compile(r"(?:^|\s)(Action[A-Za-z0-9]+)\s*=\s*\"([^\"]+)\"", re.MULTILINE)


def parse_actions(go_src: str) -> list[tuple[str, str]]:
    idx = go_src.find("// KnownAction reports")
    if idx >= 0:
        go_src = go_src[:idx]
    seen: dict[str, str] = {}
    order: list[tuple[str, str]] = []
    for name, value in ACTION_RE.findall(go_src):
        if name in seen:
            if seen[name] != value:
                raise SystemExit(f"{name}: conflicting values {seen[name]!r} vs {value!r}")
            continue
        seen[name] = value
        order.append((name, value))
    return order


def main() -> None:
    go_src = ACTIONS_GO.read_text(encoding="utf-8")
    entries = parse_actions(go_src)
    if not entries:
        raise SystemExit("no Action* constants found in actions.go")

    values = sorted({v for _, v in entries})
    DATA.mkdir(parents=True, exist_ok=True)
    (DATA / "actions.json").write_text(
        json.dumps(
            {
                "actions": [{"name": n, "value": v} for n, v in entries],
                "values": values,
                "count": len(values),
                "source": "Action* constants in actions.go",
                "generated": datetime.now(timezone.utc).isoformat(),
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    lines = [
        "// Code generated by internal/catalog/genactions.py. DO NOT EDIT.",
        "",
        "package catalog",
        "",
        "var knownActions = map[string]struct{}{",
    ]
    for value in values:
        lines.append(f"\t{json.dumps(value)}: struct{{}}{{}},")
    lines.append("}")
    lines.append("")
    lines.append("var allActions = []string{")
    for value in values:
        lines.append(f"\t{json.dumps(value)},")
    lines.append("}")
    lines.append("")
    lines.append("// AllActions returns every catalog IAM action string (sorted, deduplicated).")
    lines.append("func AllActions() []string {")
    lines.append("\treturn allActions")
    lines.append("}")
    lines.append("")
    lines.append("// KnownAction reports whether action is recognized in the current catalog.")
    lines.append("func KnownAction(action string) bool {")
    lines.append("\tif action == \"\" {")
    lines.append("\t\treturn false")
    lines.append("\t}")
    lines.append("\t_, ok := knownActions[action]")
    lines.append("\treturn ok")
    lines.append("}")
    lines.append("")
    (ROOT / "zz_actions.go").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(values)} actions ({len(entries)} consts)")


if __name__ == "__main__":
    main()
