#!/usr/bin/env python3
"""Merge SAR ConditionKeys + global seed into zz_keys.go and all_keys.json."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"

GLOBALS = [
    "aws:CurrentTime",
    "aws:EpochTime",
    "aws:PrincipalAccount",
    "aws:PrincipalArn",
    "aws:PrincipalOrgID",
    "aws:PrincipalOrgPaths",
    "aws:PrincipalTag/${TagKey}",
    "aws:PrincipalType",
    "aws:PrincipalUUID",
    "aws:RequestedRegion",
    "aws:RequestTag/${TagKey}",
    "aws:ResourceAccount",
    "aws:ResourceOrgID",
    "aws:ResourceOrgPaths",
    "aws:ResourceTag/${TagKey}",
    "aws:SecureTransport",
    "aws:SourceAccount",
    "aws:SourceArn",
    "aws:SourceIp",
    "aws:SourceOrgID",
    "aws:SourceOrgPaths",
    "aws:SourceVpc",
    "aws:SourceVpce",
    "aws:TagKeys",
    "aws:TokenIssueTime",
    "aws:UserAgent",
    "aws:userid",
    "aws:username",
    "aws:ViaAWSService",
    "aws:CalledVia",
    "aws:CalledViaFirst",
    "aws:CalledViaLast",
    "aws:MultiFactorAuthPresent",
    "aws:MultiFactorAuthAge",
    "aws:FederatedProvider",
    "aws:PrincipalIsAWSService",
    "aws:PrincipalServiceName",
    "aws:PrincipalServiceNamesList",
    "aws:referer",
    "aws:Ec2InstanceSourceVpc",
    "aws:Ec2InstanceSourcePrivateIPv4",
    "aws:SourceIdentity",
    "aws:PrincipalAssumedRole",
    "aws:AssumedRoot",
]


def main() -> None:
    DATA.mkdir(parents=True, exist_ok=True)
    service_keys: set[str] = set()
    services: list[str] = []
    skip = {
        "merged_keys.json",
        "globals_from_services.json",
        "globals.json",
        "all_keys.json",
    }
    for path in sorted(DATA.glob("*.json")):
        if path.name in skip:
            continue
        doc = json.loads(path.read_text(encoding="utf-8"))
        services.append(path.stem)
        for entry in doc.get("ConditionKeys") or []:
            if isinstance(entry, dict) and "Name" in entry:
                service_keys.add(entry["Name"])
            elif isinstance(entry, str):
                service_keys.add(entry)

    all_keys = sorted(set(GLOBALS) | service_keys)
    (DATA / "globals.json").write_text(
        json.dumps({"keys": GLOBALS, "source": "AWS global condition keys (seed)"}, indent=2)
        + "\n",
        encoding="utf-8",
    )
    (DATA / "all_keys.json").write_text(
        json.dumps(
            {
                "keys": all_keys,
                "services": services,
                "source": "servicereference ConditionKeys + global seed",
                "count": len(all_keys),
                "generated": datetime.now(timezone.utc).isoformat(),
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    lines = [
        "// Code generated by internal/catalog/conditionkeys/genkeys.py. DO NOT EDIT.",
        "",
        "package conditionkeys",
        "",
        "var knownExact = map[string]struct{}{",
    ]
    for key in all_keys:
        lines.append(f"\t{json.dumps(key)}: struct{{}}{{}},")
    lines.append("}")
    lines.append("")
    (ROOT / "zz_keys.go").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(all_keys)} keys")


if __name__ == "__main__":
    main()
